/* 
   Banco de perguntas do quiz, organizado por área (mesmos 8
   setores de areas.html) e por nível de dificuldade. Cada
   pergunta tem 4 alternativas, o índice da correta (0 a 3) e
   uma explicação curta mostrada depois da resposta.
            Estrutura:
                QUIZ_DATA[areaId][dificuldade] = [ { q, options, correct, explain }, ... ]
*/

const QUIZ_DATA = {
  programacao: {
    iniciante: [
      { q: "O que é um algoritmo?", options: ["Um tipo de vírus de computador", "Uma sequência lógica de passos para resolver um problema", "Um modelo de computador", "Um tipo de conexão de internet"], correct: 1, explain: "Algoritmo é a \"receita\" de passos que vem antes de qualquer código." },
      { q: "Qual das opções é uma linguagem de programação?", options: ["PDF", "Wi-Fi", "Python", "HTTP"], correct: 2, explain: "Python é uma linguagem de programação amplamente usada no mercado." },
      { q: "O que é \"front-end\" em desenvolvimento de software?", options: ["O banco de dados do sistema", "A parte que a pessoa usuária vê e usa", "O servidor que hospeda o site", "A rede que conecta o site"], correct: 1, explain: "Front-end é a interface visual; back-end cuida do que acontece por trás dela." },
      { q: "O que significa \"debugar\" um código?", options: ["Deixá-lo mais rápido", "Traduzi-lo para outra linguagem", "Encontrar e corrigir erros", "Apagar o programa"], correct: 2, explain: "Debugar vem de \"bug\" (erro) — é o processo de encontrar e corrigir falhas." },
      { q: "O que é \"back-end\"?", options: ["A parte visual do site", "O que processa dados e regras por trás da tela", "O nome do navegador", "Um tipo de vírus"], correct: 1, explain: "O back-end processa dados, regras de negócio e a lógica que o usuário não vê diretamente." },
    ],
    intermediario: [
      { q: "Qual a principal diferença entre uma linguagem compilada e uma interpretada?", options: ["Compiladas nunca têm erros", "Compiladas são traduzidas por inteiro antes de rodar; interpretadas são lidas linha a linha", "Interpretadas só funcionam em celular", "Não há diferença real"], correct: 1, explain: "A compilação acontece antes da execução; a interpretação acontece durante, linha a linha." },
      { q: "O que é uma \"API\"?", options: ["Um tipo de vírus de computador", "Uma interface que permite que dois sistemas troquem dados entre si", "Um navegador de internet", "Um tipo de banco de dados"], correct: 1, explain: "APIs são \"pontes\" padronizadas que permitem sistemas diferentes conversarem entre si." },
      { q: "No controle de versão de código, para que serve o Git?", options: ["Para editar imagens", "Para registrar e gerenciar o histórico de mudanças em um projeto", "Para hospedar sites", "Para testar velocidade de internet"], correct: 1, explain: "Git rastreia cada alteração no código, permitindo voltar a versões anteriores e trabalhar em equipe." },
      { q: "O que caracteriza a programação orientada a objetos?", options: ["Organizar o código em \"objetos\" que combinam dados e comportamentos", "Escrever tudo em uma única linha", "Usar apenas números no código", "Rodar o código sem testar"], correct: 0, explain: "Objetos agrupam dados (atributos) e ações (métodos) relacionados, facilitando a organização do código." },
      { q: "O que é um \"framework\" em programação?", options: ["Um vírus disfarçado", "Uma estrutura pronta que agiliza o desenvolvimento seguindo padrões definidos", "Um tipo de arquivo de imagem", "Um sistema operacional"], correct: 1, explain: "Frameworks oferecem uma base pronta (padrões, ferramentas) para não reinventar tudo do zero." },
    ],
    avancado: [
      { q: "Em bancos de dados relacionais, o que é uma \"chave estrangeira\" (foreign key)?", options: ["A senha do banco de dados", "Um campo que referencia a chave primária de outra tabela, criando relação entre elas", "Um tipo de criptografia", "O nome do servidor"], correct: 1, explain: "A chave estrangeira conecta tabelas diferentes, mantendo a integridade relacional dos dados." },
      { q: "O que é a complexidade de tempo de um algoritmo (notação O(n))?", options: ["O tempo que o programador levou para escrevê-lo", "Uma forma de estimar como o tempo de execução cresce conforme o tamanho da entrada cresce", "O tempo de vida útil do software", "A quantidade de erros no código"], correct: 1, explain: "A notação Big O descreve como o desempenho de um algoritmo se comporta à medida que os dados aumentam." },
      { q: "O que é \"programação assíncrona\"?", options: ["Escrever código sem seguir nenhuma ordem", "Executar tarefas sem bloquear o restante do programa enquanto se espera uma resposta", "Programar sozinho, sem equipe", "Um tipo de linguagem extinta"], correct: 1, explain: "Código assíncrono permite continuar executando outras tarefas enquanto uma operação demorada termina." },
      { q: "Em arquitetura de software, o que caracteriza \"microsserviços\"?", options: ["Programas pequenos demais para funcionar", "Dividir um sistema em serviços independentes que se comunicam entre si", "Um único bloco de código gigante", "Um tipo de vírus de rede"], correct: 1, explain: "Cada microsserviço cuida de uma responsabilidade específica e pode ser desenvolvido e escalado separadamente." },
      { q: "O que é \"injeção de SQL\" (SQL Injection)?", options: ["Uma forma de acelerar consultas ao banco", "Uma técnica de ataque que insere comandos maliciosos em campos de entrada para manipular o banco de dados", "Um tipo de backup automático", "Um método de criptografia"], correct: 1, explain: "É um dos ataques mais comuns a aplicações web mal protegidas, explorando campos de entrada sem validação." },
    ],
  },

  ia: {
    iniciante: [
      { q: "O que é Inteligência Artificial, de forma simples?", options: ["Um tipo de robô físico apenas", "Sistemas que simulam capacidades humanas como aprender e decidir", "Um vírus de computador", "Um tipo de internet mais rápida"], correct: 1, explain: "IA é a área que cria sistemas capazes de aprender, reconhecer padrões e tomar decisões." },
      { q: "O que é \"IA generativa\"?", options: ["IA que só apaga arquivos", "IA capaz de criar conteúdo novo, como texto e imagem", "Um tipo de antivírus", "Uma rede social"], correct: 1, explain: "A IA generativa é a tecnologia por trás de assistentes que escrevem textos, criam imagens e códigos." },
      { q: "Machine Learning (aprendizado de máquina) é:", options: ["Quando a máquina aprende a partir de dados e exemplos", "Quando um técnico programa cada resposta manualmente", "Um tipo de hardware", "Um tipo de vírus"], correct: 0, explain: "Em vez de regras fixas, o sistema identifica padrões a partir de muitos exemplos." },
      { q: "Qual destes é um exemplo comum de uso de IA no dia a dia?", options: ["Recomendações de vídeos em plataformas de streaming", "O relógio de parede", "Uma calculadora simples", "Um cabo de rede"], correct: 0, explain: "Sistemas de recomendação usam IA para sugerir conteúdo com base no seu comportamento." },
      { q: "Por que os dados usados para treinar uma IA são importantes?", options: ["Não influenciam em nada o resultado", "A qualidade da IA depende diretamente da qualidade desses dados", "Servem só para ocupar espaço", "São usados apenas depois que a IA já está pronta"], correct: 1, explain: "Dados de baixa qualidade ou incompletos levam a resultados de baixa qualidade." },
    ],
    intermediario: [
      { q: "O que são \"vieses\" em sistemas de IA?", options: ["Erros de digitação no código", "Padrões problemáticos que a IA reproduz por estarem presentes nos dados de treinamento", "Um tipo de proteção contra hackers", "Falta de conexão à internet"], correct: 1, explain: "Se os dados de treino contêm desigualdades ou distorções, a IA tende a reproduzi-las." },
      { q: "O que diferencia aprendizado supervisionado de não supervisionado?", options: ["Não há diferença", "No supervisionado, os dados vêm com respostas certas conhecidas; no não supervisionado, não", "Supervisionado é sempre mais lento", "Não supervisionado não usa dados"], correct: 1, explain: "No supervisionado, o modelo aprende comparando suas respostas com respostas já conhecidas." },
      { q: "O que é uma rede neural artificial, de forma geral?", options: ["Uma rede Wi-Fi doméstica", "Um modelo inspirado no funcionamento de neurônios, usado para reconhecer padrões", "Um cabo de fibra óptica", "Um antivírus"], correct: 1, explain: "Redes neurais são a base de boa parte da IA moderna, incluindo a IA generativa." },
      { q: "O que é um \"modelo de linguagem\" (usado em chatbots de IA)?", options: ["Um dicionário impresso", "Um sistema treinado para prever e gerar texto com base em padrões da linguagem", "Um tradutor automático apenas", "Um corretor ortográfico simples"], correct: 1, explain: "Modelos de linguagem aprendem estatisticamente como as palavras se relacionam para gerar texto coerente." },
      { q: "Segundo pesquisas recentes no Brasil, o uso de IA generativa está distribuído de forma:", options: ["Totalmente igual entre todas as classes sociais", "Desigual — maior entre pessoas de maior renda e escolaridade", "Maior nas classes de menor renda", "Restrita apenas a empresas"], correct: 1, explain: "A pesquisa TIC Domicílios 2025 (CGI.br/NIC.br) mostra 69% de uso na classe A contra 16% nas classes D/E." },
    ],
    avancado: [
      { q: "O que é \"overfitting\" em Machine Learning?", options: ["Quando o modelo aprende demais os dados de treino e perde a capacidade de generalizar para dados novos", "Quando o modelo é rápido demais", "Quando faltam dados de treino", "Um tipo de erro de hardware"], correct: 0, explain: "O modelo \"decora\" os exemplos de treino, mas erra em situações novas." },
      { q: "Redes neurais convolucionais (CNNs) são mais usadas para:", options: ["Processamento de texto apenas", "Reconhecimento de padrões em imagens", "Envio de e-mails", "Backup de arquivos"], correct: 1, explain: "CNNs são especialmente eficazes para identificar padrões visuais em imagens." },
      { q: "O que caracteriza a técnica de \"fine-tuning\" em modelos de IA?", options: ["Apagar o modelo e recomeçar do zero", "Ajustar um modelo já treinado com dados específicos para uma tarefa mais restrita", "Aumentar a velocidade da internet", "Trocar o hardware do servidor"], correct: 1, explain: "O fine-tuning aproveita um modelo genérico já treinado e o especializa para um uso específico." },
      { q: "O que é \"alucinação\" em modelos de IA generativa?", options: ["Quando o sistema trava completamente", "Quando o modelo gera informação incorreta ou inventada com aparência de verdadeira", "Um recurso de segurança", "Um tipo de vírus"], correct: 1, explain: "É por isso que respostas de IA generativa sempre merecem verificação em fontes confiáveis." },
      { q: "Em IA, o que é um \"prompt\"?", options: ["O nome do servidor que roda o modelo", "A instrução ou pergunta dada pelo usuário para orientar a resposta do modelo", "Um tipo de erro do sistema", "O tempo de resposta da IA"], correct: 1, explain: "A qualidade do prompt influencia diretamente a qualidade da resposta gerada." },
    ],
  },

  ciberseguranca: {
    iniciante: [
      { q: "O que é phishing?", options: ["Um tipo de jogo online", "Mensagens falsas que imitam empresas ou pessoas confiáveis para roubar dados", "Um antivírus", "Um tipo de rede Wi-Fi"], correct: 1, explain: "Phishing tenta enganar a vítima para que ela mesma entregue senhas ou dados." },
      { q: "Qual é uma boa prática básica de segurança digital?", options: ["Usar a mesma senha em todos os sites", "Ativar a autenticação em duas etapas", "Nunca atualizar os aplicativos", "Compartilhar senhas com desconhecidos"], correct: 1, explain: "A autenticação em duas etapas adiciona uma camada extra de proteção além da senha." },
      { q: "O que é um \"malware\"?", options: ["Um tipo de hardware caro", "Um programa malicioso criado para causar dano ou roubar dados", "Um tipo de backup", "Um serviço de nuvem"], correct: 1, explain: "Malware é o termo geral para softwares maliciosos, incluindo vírus e ransomware." },
      { q: "Ransomware é um tipo de ataque que:", options: ["Acelera o computador", "Sequestra os dados da vítima e cobra resgate para devolvê-los", "Melhora a conexão de internet", "Cria backups automáticos"], correct: 1, explain: "Por isso backups regulares e atualizados são uma das melhores defesas contra ransomware." },
      { q: "Por que fazer backups regulares é importante?", options: ["Não é importante", "Para recuperar dados em caso de perda, roubo ou ataque", "Para deixar o computador mais lento", "Só serve para fotos"], correct: 1, explain: "Backups são a rede de segurança que permite recuperar informações mesmo após um incidente." },
    ],
    intermediario: [
      { q: "O que representa a tríade CIA em segurança da informação?", options: ["Computador, Internet, Aplicativo", "Confidencialidade, Integridade e Disponibilidade", "Código, Interface e Acesso", "Certificado, Identidade e Autorização"], correct: 1, explain: "Esses três pilares orientam praticamente toda estratégia de segurança da informação." },
      { q: "O que é engenharia social em ataques cibernéticos?", options: ["Um tipo de rede social", "Manipular pessoas psicologicamente para obter informações ou acessos indevidos", "Uma lei de proteção de dados", "Um tipo de firewall"], correct: 1, explain: "Muitos ataques exploram a confiança humana, não só falhas técnicas." },
      { q: "Para que serve um firewall?", options: ["Aumentar a velocidade da internet", "Filtrar e controlar o tráfego de rede, bloqueando acessos não autorizados", "Armazenar senhas", "Enviar e-mails automaticamente"], correct: 1, explain: "O firewall atua como uma barreira entre a rede confiável e ameaças externas." },
      { q: "O que é autenticação em duas etapas (2FA)?", options: ["Usar duas senhas iguais", "Uma camada extra de verificação além da senha, como um código enviado ao celular", "Fazer login duas vezes seguidas", "Trocar de senha duas vezes por ano"], correct: 1, explain: "Mesmo que a senha vaze, o invasor ainda precisaria do segundo fator para acessar a conta." },
      { q: "O que é criptografia, de forma simples?", options: ["Apagar dados permanentemente", "Transformar informação em um código para que só quem tem a chave certa consiga lê-la", "Comprimir arquivos para ocupar menos espaço", "Um tipo de vírus"], correct: 1, explain: "A criptografia protege dados em trânsito e armazenados de olhares não autorizados." },
    ],
    avancado: [
      { q: "O que é um ataque de \"força bruta\" (brute force)?", options: ["Um ataque físico ao servidor", "Tentar sistematicamente todas as combinações possíveis de senha até acertar", "Um tipo de vírus que danifica o hardware", "Um ataque que usa apenas engenharia social"], correct: 1, explain: "Senhas longas e complexas tornam esse tipo de ataque impraticável." },
      { q: "O que caracteriza uma vulnerabilidade \"zero-day\"?", options: ["Uma falha corrigida há mais de um ano", "Uma falha de segurança explorada antes de o fabricante ter chance de corrigi-la", "Um vírus sem nenhum efeito", "Um tipo de senha fraca"], correct: 1, explain: "O nome vem do fato de o fabricante ter \"zero dias\" de aviso antes da exploração." },
      { q: "O que é um ataque DDoS?", options: ["Um vírus que apaga arquivos silenciosamente", "Sobrecarregar um servidor com tráfego excessivo vindo de múltiplas fontes até deixá-lo indisponível", "Uma técnica de criptografia", "Um tipo de backup na nuvem"], correct: 1, explain: "O \"D\" duplo vem de \"Distributed\": o ataque parte de muitas fontes ao mesmo tempo." },
      { q: "Em gestão de segurança, o que é o princípio do \"menor privilégio\"?", options: ["Dar a todos os usuários acesso total ao sistema", "Conceder a cada usuário apenas o acesso mínimo necessário para sua função", "Usar a senha mais simples possível", "Desligar o firewall para melhorar a performance"], correct: 1, explain: "Isso limita o estrago possível caso uma conta seja comprometida." },
      { q: "O que é um \"honeypot\" em segurança da informação?", options: ["Um tipo de senha", "Um sistema-isca criado para atrair e estudar atacantes, protegendo os sistemas reais", "Um antivírus gratuito", "Um tipo de criptografia forte"], correct: 1, explain: "Honeypots ajudam equipes de segurança a entender táticas de ataque em um ambiente controlado." },
    ],
  },

  nuvem: {
    iniciante: [
      { q: "O que é computação em nuvem, de forma simples?", options: ["Um tipo de previsão do tempo", "O uso de servidores e programas disponibilizados pela internet, em vez de só no computador local", "Um tipo de vírus", "Uma marca de computador"], correct: 1, explain: "A \"nuvem\" é, na prática, infraestrutura de terceiros acessada pela internet." },
      { q: "Qual destes é um exemplo de serviço que usa computação em nuvem?", options: ["Uma calculadora de mesa", "Google Drive", "Uma TV antiga sem internet", "Um rádio AM"], correct: 1, explain: "O Google Drive armazena e sincroniza arquivos em servidores na nuvem." },
      { q: "O que significa a nuvem ser \"pública\"?", options: ["Que qualquer um pode invadir os dados", "Que a infraestrutura é compartilhada entre vários clientes diferentes", "Que não tem custo nenhum", "Que só funciona em local público"], correct: 1, explain: "Nuvem pública não significa dados abertos — significa infraestrutura compartilhada, com isolamento entre clientes." },
      { q: "Qual a vantagem da \"escalabilidade\" na nuvem?", options: ["O preço nunca muda", "É possível aumentar ou diminuir recursos conforme a necessidade, pagando pelo uso", "Os dados ficam mais lentos", "Não existe essa vantagem"], correct: 1, explain: "Empresas evitam pagar por capacidade ociosa e ajustam recursos conforme a demanda real." },
      { q: "O que é armazenamento em nuvem?", options: ["Guardar arquivos fisicamente em um pen-drive", "Guardar arquivos em servidores acessíveis pela internet, de qualquer lugar", "Um tipo de impressora", "Um cabo de conexão"], correct: 1, explain: "Isso permite acessar os mesmos arquivos de diferentes dispositivos, a qualquer momento." },
    ],
    intermediario: [
      { q: "O que caracteriza o modelo \"SaaS\" (Software as a Service)?", options: ["O usuário instala e mantém o software localmente", "O software é acessado pronto para uso, direto pela internet, sem precisar instalar ou manter", "É um tipo de hardware", "Só existe para jogos"], correct: 1, explain: "Exemplos comuns de SaaS: Gmail, Netflix, e ferramentas de escritório online." },
      { q: "Qual a diferença entre \"IaaS\" e \"PaaS\"?", options: ["Não há diferença", "IaaS entrega infraestrutura básica (servidores, redes); PaaS entrega uma plataforma pronta para desenvolver aplicações", "IaaS é sempre gratuito", "PaaS não usa internet"], correct: 1, explain: "PaaS já inclui ferramentas de desenvolvimento prontas sobre a infraestrutura." },
      { q: "O que é uma nuvem híbrida?", options: ["Uma nuvem que não funciona corretamente", "A combinação de nuvem pública e privada trabalhando juntas", "Um tipo de vírus de nuvem", "Uma nuvem só para celulares"], correct: 1, explain: "Empresas usam nuvem híbrida para equilibrar custo, controle e segurança conforme o dado ou processo." },
      { q: "Por que empresas migram sistemas para a nuvem?", options: ["Para aumentar custos fixos com hardware próprio", "Para reduzir custos com infraestrutura própria e ganhar flexibilidade", "Não há motivo real", "Só por modismo, sem benefício prático"], correct: 1, explain: "A nuvem reduz a necessidade de investir e manter servidores físicos próprios." },
      { q: "O que é \"latência\" em serviços de nuvem?", options: ["O preço do serviço", "O tempo que os dados levam para ir e voltar entre o usuário e o servidor", "O tamanho do arquivo armazenado", "O número de usuários conectados"], correct: 1, explain: "Latência mais baixa significa resposta mais rápida do serviço." },
    ],
    avancado: [
      { q: "O que é \"computação sem servidor\" (serverless)?", options: ["Um sistema que não usa nenhum servidor em lugar nenhum", "Um modelo em que o provedor gerencia toda a infraestrutura, e o desenvolvedor só se preocupa com o código", "Um tipo de nuvem exclusiva para jogos", "Um sistema sem conexão à internet"], correct: 1, explain: "Servidores continuam existindo — só ficam totalmente abstraídos da responsabilidade do desenvolvedor." },
      { q: "O que são \"containers\" (como o Docker) em computação em nuvem?", options: ["Caixas físicas de transporte de servidores", "Pacotes que empacotam uma aplicação com tudo que ela precisa para rodar de forma isolada e consistente", "Um tipo de vírus", "Um serviço de streaming"], correct: 1, explain: "Containers garantem que a aplicação rode do mesmo jeito em qualquer ambiente compatível." },
      { q: "O que caracteriza uma arquitetura \"multi-cloud\"?", options: ["Usar um único provedor de nuvem para tudo", "Usar serviços de mais de um provedor de nuvem simultaneamente", "Não usar nenhuma nuvem", "Um erro de configuração"], correct: 1, explain: "Isso reduz a dependência de um único fornecedor e pode melhorar resiliência." },
      { q: "O que é \"elasticidade\" em computação em nuvem?", options: ["O mesmo que backup", "A capacidade de ajustar recursos automaticamente e em tempo real conforme a demanda muda", "Um tipo de criptografia", "A cor da interface do provedor"], correct: 1, explain: "Elasticidade permite lidar com picos de acesso sem intervenção manual constante." },
      { q: "Em segurança na nuvem, o que é o \"modelo de responsabilidade compartilhada\"?", options: ["O provedor cuida de tudo sozinho", "Provedor e cliente dividem responsabilidades de segurança, cada um cuidando de partes diferentes", "O cliente cuida de tudo sozinho", "Não existe esse conceito"], correct: 1, explain: "Em geral, o provedor protege a infraestrutura; o cliente é responsável por configurar e proteger seus próprios dados e acessos." },
    ],
  },

  dados: {
    iniciante: [
      { q: "O que é ciência de dados, de forma simples?", options: ["Um tipo de vírus de computador", "A área que transforma dados em informações úteis para decisões", "Um sistema operacional", "Um tipo de rede social"], correct: 1, explain: "Ciência de dados combina estatística, programação e conhecimento de negócio." },
      { q: "O que é \"Big Data\"?", options: ["Um único arquivo pequeno", "Volumes de dados grandes e complexos demais para análise manual", "Um tipo de vírus", "Um navegador de internet"], correct: 1, explain: "Big Data exige ferramentas específicas para ser coletado, armazenado e analisado." },
      { q: "Qual etapa geralmente consome mais tempo em um projeto de dados?", options: ["Apresentar o resultado final", "Limpar e organizar os dados", "Ligar o computador", "Enviar e-mails"], correct: 1, explain: "Dados do mundo real costumam vir incompletos, duplicados ou inconsistentes." },
      { q: "Qual destes é um exemplo comum de uso de ciência de dados?", options: ["Sistemas de recomendação de filmes e séries", "Uma lâmpada comum", "Um relógio analógico", "Uma régua"], correct: 0, explain: "Plataformas de streaming analisam dados de comportamento para sugerir conteúdo." },
      { q: "O que significa \"visualizar dados\"?", options: ["Apagar os dados depois de usá-los", "Representar dados em gráficos e imagens para facilitar o entendimento", "Guardar dados em papel", "Criptografar os dados"], correct: 1, explain: "Gráficos tornam padrões complexos muito mais fáceis de interpretar rapidamente." },
    ],
    intermediario: [
      { q: "Qual a diferença entre dados estruturados e não estruturados?", options: ["Não existe diferença", "Estruturados seguem um formato organizado (como tabelas); não estruturados não têm formato fixo (como textos e imagens)", "Não estruturados são sempre menores", "Estruturados não podem ser analisados"], correct: 1, explain: "E-mails, vídeos e áudios são exemplos comuns de dados não estruturados." },
      { q: "O que é uma \"correlação\" entre duas variáveis?", options: ["Prova de que uma causa a outra", "Uma relação estatística entre elas, que não implica necessariamente causa e efeito", "Um tipo de gráfico apenas", "Um erro de cálculo"], correct: 1, explain: "\"Correlação não implica causalidade\" é um dos princípios mais importantes da análise de dados." },
      { q: "O que é um \"outlier\" (valor discrepante) em uma análise de dados?", options: ["O valor mais comum do conjunto", "Um dado que se destaca muito dos demais, podendo indicar erro ou algo incomum", "O total de dados coletados", "Um tipo de gráfico"], correct: 1, explain: "Outliers merecem investigação: podem ser erro de coleta ou um evento real relevante." },
      { q: "Para que serve um \"dashboard\" de dados?", options: ["Para armazenar senhas", "Para exibir indicadores e métricas de forma visual e organizada", "Para enviar e-mails em massa", "Para proteger contra vírus"], correct: 1, explain: "Dashboards ajudam equipes a acompanhar métricas importantes em tempo real, sem precisar analisar dados brutos." },
      { q: "O que é um \"banco de dados relacional\"?", options: ["Um tipo de rede social", "Um sistema que organiza dados em tabelas relacionadas entre si", "Um tipo de vírus", "Um navegador"], correct: 1, explain: "As relações entre tabelas evitam repetição de dados e mantêm consistência." },
    ],
    avancado: [
      { q: "O que é \"ETL\" em engenharia de dados?", options: ["Um tipo de linguagem de programação", "O processo de Extrair, Transformar e Carregar dados entre sistemas", "Um antivírus", "Um protocolo de internet"], correct: 1, explain: "ETL é a base de como dados de fontes diferentes chegam prontos para análise." },
      { q: "O que caracteriza um modelo de dados em \"data warehouse\"?", options: ["Armazenamento temporário e não estruturado", "Um repositório central, organizado, otimizado para consultas e análises históricas", "Um tipo de vírus", "Um aplicativo de mensagens"], correct: 1, explain: "Data warehouses consolidam dados de várias fontes para análises estratégicas de longo prazo." },
      { q: "O que é \"A/B testing\" em análise de dados?", options: ["Comparar duas versões de algo para ver qual performa melhor com base em dados reais", "Um teste de velocidade de internet", "Um tipo de backup", "Um erro de sistema"], correct: 0, explain: "É amplamente usado para decidir, com evidência, qual versão de um produto funciona melhor." },
      { q: "O que é \"viés de amostragem\" (sampling bias)?", options: ["Quando a amostra usada não representa bem a população real, distorcendo os resultados", "Um tipo de gráfico", "Um erro de digitação", "Um tipo de criptografia"], correct: 0, explain: "Uma amostra mal escolhida pode levar a conclusões erradas sobre todo o grupo estudado." },
      { q: "Em Machine Learning aplicado a dados, o que é \"feature engineering\"?", options: ["Construir o hardware do servidor", "Selecionar e transformar variáveis dos dados para melhorar o desempenho do modelo", "Testar a velocidade da internet", "Um tipo de vírus"], correct: 1, explain: "Boas features (variáveis) bem construídas costumam impactar mais o resultado do que o algoritmo escolhido." },
    ],
  },

  redes: {
    iniciante: [
      { q: "O que é uma rede de computadores?", options: ["Um tipo de vírus", "Um conjunto de dispositivos conectados entre si para trocar dados", "Um programa de edição de texto", "Um tipo de impressora"], correct: 1, explain: "Redes existem em vários tamanhos: de uma casa até a internet mundial inteira." },
      { q: "Qual a diferença entre Wi-Fi e dados móveis?", options: ["São exatamente a mesma coisa", "Wi-Fi conecta por rede local sem fio; dados móveis usam a rede da operadora de celular", "Wi-Fi só funciona fora de casa", "Dados móveis não usam internet"], correct: 1, explain: "Ambos dão acesso à internet, mas por infraestruturas diferentes." },
      { q: "O que representa a sigla \"5G\"?", options: ["Um tipo de vírus", "A quinta geração de tecnologia de rede móvel", "Um programa de segurança", "Um tipo de cabo USB"], correct: 1, explain: "Cada geração de rede móvel (3G, 4G, 5G) traz mais velocidade e menos atraso na conexão." },
      { q: "O que é um roteador (router)?", options: ["Um tipo de vírus de computador", "Um equipamento que distribui a conexão de internet entre os dispositivos de uma rede", "Um programa de edição de vídeo", "Um tipo de bateria"], correct: 1, explain: "É o equipamento que costuma ficar em casa distribuindo Wi-Fi para os dispositivos." },
      { q: "Por que a qualidade da conexão de internet importa, além de só \"ter\" acesso?", options: ["Não importa, ter acesso já basta", "Porque velocidade, estabilidade e latência afetam diretamente o uso no dia a dia", "Só importa para jogos", "A qualidade nunca varia"], correct: 1, explain: "Uma conexão instável ou lenta limita o que a pessoa consegue fazer online, mesmo estando \"conectada\"." },
    ],
    intermediario: [
      { q: "O que é \"backbone\" da internet?", options: ["Um tipo de vírus de rede", "A rede de cabos de alta capacidade que interliga grandes trechos da internet mundial", "Um tipo de roteador doméstico", "Um antivírus"], correct: 1, explain: "O backbone é a espinha dorsal por onde passa o grosso do tráfego da internet." },
      { q: "O que é \"latência\" em uma conexão de rede?", options: ["A velocidade máxima de download", "O tempo de atraso entre o envio e a chegada de um dado", "O preço do plano de internet", "O número de dispositivos conectados"], correct: 1, explain: "Latência baixa é essencial para usos em tempo real, como chamadas de vídeo e jogos online." },
      { q: "Qual a diferença entre uma rede LAN e uma WAN?", options: ["Não existe diferença", "LAN é uma rede local (ex: de uma casa ou escritório); WAN cobre áreas geográficas muito maiores", "LAN é sempre sem fio", "WAN não usa internet"], correct: 1, explain: "A própria internet é o maior exemplo de WAN que existe." },
      { q: "O que é um endereço IP?", options: ["Um tipo de senha de Wi-Fi", "Um identificador numérico que localiza um dispositivo em uma rede", "O nome do roteador", "Um tipo de cabo"], correct: 1, explain: "Assim como um endereço postal, o IP identifica \"onde\" cada dispositivo está na rede." },
      { q: "O que faz um DNS (Sistema de Nomes de Domínio)?", options: ["Aumenta a velocidade da internet", "Traduz nomes de sites (como \"google.com\") em endereços IP que os computadores entendem", "Protege contra vírus", "Armazena senhas"], correct: 1, explain: "Sem o DNS, seria preciso decorar sequências de números para acessar cada site." },
    ],
    avancado: [
      { q: "O que é uma VPN (Rede Virtual Privada)?", options: ["Um tipo de vírus", "Uma conexão criptografada que protege e anonimiza o tráfego de dados entre o dispositivo e a internet", "Um tipo de roteador físico", "Um serviço de streaming"], correct: 1, explain: "VPNs são usadas tanto por empresas quanto por pessoas físicas para proteger a privacidade da conexão." },
      { q: "O que caracteriza o protocolo TCP/IP?", options: ["Um único cabo físico de rede", "O conjunto de regras que define como os dados são divididos, endereçados e entregues pela internet", "Um tipo de antivírus", "Um serviço de nuvem"], correct: 1, explain: "TCP/IP é o protocolo fundamental que faz a internet global funcionar de forma padronizada." },
      { q: "O que é \"balanceamento de carga\" (load balancing) em redes?", options: ["Aumentar o peso físico do servidor", "Distribuir o tráfego entre vários servidores para evitar sobrecarga em um único ponto", "Um tipo de criptografia", "Reduzir o número de usuários"], correct: 1, explain: "Isso mantém serviços online estáveis mesmo com grande volume de acessos simultâneos." },
      { q: "Em redes móveis, o que caracteriza principalmente a evolução do 4G para o 5G?", options: ["Menor velocidade e mais atraso", "Maior velocidade, menor latência e capacidade de conectar muito mais dispositivos simultaneamente", "Nenhuma mudança real", "Uso exclusivo para ligações de voz"], correct: 1, explain: "Essas melhorias são o que viabiliza tecnologias como IoT em larga escala." },
      { q: "O que é um firewall de próxima geração (NGFW)?", options: ["Um roteador doméstico comum", "Um firewall que combina filtragem tradicional com inspeção mais profunda de tráfego e ameaças", "Um tipo de cabo de fibra óptica", "Um serviço de backup"], correct: 1, explain: "NGFWs analisam o conteúdo do tráfego, não só origem e destino, para detectar ameaças mais sofisticadas." },
    ],
  },

  iot: {
    iniciante: [
      { q: "O que é Internet das Coisas (IoT)?", options: ["Um tipo de vírus", "Objetos físicos do dia a dia conectados à internet, capazes de coletar e trocar dados", "Um navegador de internet", "Um tipo de rede social"], correct: 1, explain: "Praticamente qualquer objeto com sensor e conexão pode fazer parte da IoT." },
      { q: "Qual destes é um exemplo de dispositivo IoT?", options: ["Uma lâmpada inteligente controlada pelo celular", "Uma lâmpada comum sem conexão", "Um livro impresso", "Uma caneta"], correct: 0, explain: "A conexão à internet e a capacidade de troca de dados são o que define um dispositivo IoT." },
      { q: "Para que servem os sensores em dispositivos IoT?", options: ["Para decorar o produto", "Para captar informações do ambiente, como temperatura ou movimento", "Para aumentar o preço", "Não têm função real"], correct: 1, explain: "Sensores são os \"sentidos\" que permitem ao dispositivo perceber o ambiente ao redor." },
      { q: "O que é \"automação residencial\" (casa inteligente)?", options: ["Uma casa sem eletricidade", "O uso de dispositivos conectados para automatizar tarefas da casa, como iluminação e temperatura", "Um tipo de seguro residencial", "Um aplicativo de decoração"], correct: 1, explain: "Esses dispositivos costumam ser controlados remotamente por aplicativo ou comando de voz." },
      { q: "Por que a IoT depende de conexão à internet?", options: ["Não depende, funciona offline sempre", "Porque os dispositivos precisam transmitir e receber dados para funcionar de forma conectada", "Só para atualizar o relógio", "É apenas um recurso opcional sem uso real"], correct: 1, explain: "Sem conexão, o dispositivo perde a capacidade de trocar dados com outros sistemas." },
    ],
    intermediario: [
      { q: "O que caracteriza um \"wearable\" no contexto de IoT?", options: ["Um eletrodoméstico grande", "Um dispositivo vestível, como uma pulseira ou relógio inteligente, conectado à internet", "Um tipo de cabo", "Um servidor de dados"], correct: 1, explain: "Wearables costumam monitorar dados de saúde e atividade em tempo real." },
      { q: "Por que o 5G é importante para o crescimento da IoT?", options: ["Não tem relação nenhuma", "Porque viabiliza conectar um número muito maior de dispositivos simultaneamente, com mais velocidade", "Porque é mais caro", "Porque desliga os dispositivos automaticamente"], correct: 1, explain: "Redes anteriores têm limites de quantos dispositivos conseguem conectar bem na mesma área." },
      { q: "O que é IoT industrial (IIoT)?", options: ["O uso de sensores e dispositivos conectados em fábricas e processos industriais para monitorar e automatizar operações", "Um tipo de rede social empresarial", "Um vírus que ataca indústrias", "Um sistema de contabilidade"], correct: 0, explain: "IIoT é usada para prever falhas em máquinas antes que elas aconteçam, entre outros usos." },
      { q: "Qual é um desafio comum de segurança em dispositivos IoT?", options: ["Eles são sempre totalmente seguros", "Muitos dispositivos têm proteções fracas, o que pode abrir brechas na rede", "Não existe nenhum risco", "Eles não se conectam a redes"], correct: 1, explain: "Dispositivos IoT mal protegidos podem virar porta de entrada para ataques maiores." },
      { q: "O que faz um sensor IoT de temperatura em uma fazenda inteligente (agricultura de precisão)?", options: ["Decora a plantação", "Coleta dados do ambiente para ajudar a otimizar irrigação e cultivo", "Substitui o agricultor completamente", "Não tem aplicação real"], correct: 1, explain: "A agricultura de precisão usa dados de sensores para tomar decisões mais eficientes sobre a lavoura." },
    ],
    avancado: [
      { q: "O que é \"edge computing\" no contexto de IoT?", options: ["Processar os dados na nuvem apenas", "Processar dados próximo de onde são gerados (no próprio dispositivo ou perto dele), reduzindo latência", "Um tipo de vírus", "Um protocolo de e-mail"], correct: 1, explain: "Isso reduz o tempo de resposta e o volume de dados enviados até um servidor distante." },
      { q: "Qual protocolo é comumente usado para comunicação leve entre dispositivos IoT com pouca energia?", options: ["HTTP apenas", "MQTT", "FTP", "SMTP"], correct: 1, explain: "O MQTT foi criado justamente para funcionar bem em dispositivos com recursos limitados." },
      { q: "O que caracteriza uma rede LPWAN (rede de longo alcance e baixa potência) usada em IoT?", options: ["Alta velocidade e curto alcance, como o Wi-Fi", "Longo alcance com baixo consumo de energia, ideal para sensores que enviam poucos dados", "Uso exclusivo para vídeo em alta definição", "Conexão apenas por cabo"], correct: 1, explain: "LPWANs permitem que sensores durem anos com bateria, enviando pequenas quantidades de dados." },
      { q: "Segundo a regulação brasileira (Decreto nº 9.854/2019), a IoT é tratada como:", options: ["Um tema irrelevante para políticas públicas", "Uma prioridade estratégica para o desenvolvimento do país", "Uma tecnologia proibida", "Um risco a ser eliminado"], correct: 1, explain: "O decreto instituiu o Plano Nacional de Internet das Coisas como política de Estado." },
      { q: "O que é \"interoperabilidade\" entre dispositivos IoT?", options: ["A capacidade de dispositivos de fabricantes diferentes se comunicarem e funcionarem juntos", "A velocidade máxima de um sensor", "O preço médio dos dispositivos", "Um tipo de bateria"], correct: 0, explain: "Sem interoperabilidade, cada fabricante criaria um \"ecossistema fechado\" incompatível com os demais." },
    ],
  },

  imersivas: {
    iniciante: [
      { q: "O que é Realidade Virtual (RV)?", options: ["Um filtro de câmera simples", "Um ambiente totalmente digital e imersivo, geralmente visto por um óculos especial", "Um tipo de vírus", "Uma rede social"], correct: 1, explain: "A RV substitui completamente a percepção do ambiente real enquanto está em uso." },
      { q: "O que é Realidade Aumentada (RA)?", options: ["O mesmo que Realidade Virtual", "A sobreposição de elementos digitais ao mundo real, sem substituí-lo", "Um tipo de jogo de tabuleiro", "Um sistema de backup"], correct: 1, explain: "Filtros de câmera em redes sociais são um exemplo popular de RA." },
      { q: "Qual equipamento é mais associado à Realidade Virtual?", options: ["Um óculos ou headset imersivo", "Uma caneta comum", "Um teclado sem fio", "Uma impressora"], correct: 0, explain: "O headset isola a visão do usuário para criar a sensação de estar em outro ambiente." },
      { q: "Qual destes é um exemplo comum de Realidade Aumentada usada em celulares?", options: ["Filtros de câmera que adicionam elementos digitais à imagem real", "Uma calculadora comum", "Um alarme", "Uma lanterna"], correct: 0, explain: "O celular capta a imagem real pela câmera e sobrepõe elementos digitais em tempo real." },
      { q: "Além de jogos, para que mais a Realidade Virtual e Aumentada podem ser usadas?", options: ["Não têm outros usos", "Treinamentos, educação e simulações", "Apenas para fotos", "Apenas para chamadas de vídeo"], correct: 1, explain: "Empresas e escolas já usam essas tecnologias para treinar pessoas em situações simuladas e seguras." },
    ],
    intermediario: [
      { q: "Qual a principal diferença de experiência entre RV e RA?", options: ["Não há diferença nenhuma", "A RV isola a pessoa em um ambiente simulado; a RA mantém o mundo real visível, adicionando camadas de informação", "RA sempre precisa de óculos especiais", "RV funciona só em computadores"], correct: 1, explain: "Essa diferença de imersão define para quais usos cada tecnologia é mais indicada." },
      { q: "Como empresas de varejo usam Realidade Aumentada?", options: ["Não é usada no varejo", "Para provadores virtuais, permitindo \"experimentar\" produtos digitalmente antes da compra", "Apenas para propaganda impressa", "Só para controle de estoque"], correct: 1, explain: "Provadores virtuais ajudam a reduzir devoluções e aumentar a confiança na compra online." },
      { q: "O que é \"realidade mista\" (RM)?", options: ["O mesmo que realidade aumentada", "A combinação de elementos do mundo real e virtual que podem interagir entre si em tempo real", "Um tipo de jogo antigo", "Um erro de sistema"], correct: 1, explain: "Na realidade mista, objetos virtuais podem reagir a obstáculos e superfícies do mundo real." },
      { q: "Por que empresas usam RV para treinamentos corporativos?", options: ["Não é usada para isso", "Porque permite simular situações de risco ou de alto custo de forma segura e repetível", "Porque é obrigatório por lei em todos os setores", "Porque substitui totalmente o RH"], correct: 1, explain: "Simular um incêndio ou uma cirurgia em RV é muito mais seguro e barato do que na prática real repetidas vezes." },
      { q: "O que é necessário, tecnicamente, para rodar experiências de RV mais avançadas?", options: ["Apenas uma conexão de internet lenta", "Hardware com bom processamento gráfico, já que a imersão exige renderização em tempo real", "Nenhum hardware especial", "Apenas um teclado"], correct: 1, explain: "Gerar dois pontos de vista (um para cada olho) em alta taxa de quadros exige processamento gráfico robusto." },
    ],
    avancado: [
      { q: "O que é \"campo de visão\" (FOV) em dispositivos de RV, e por que importa?", options: ["O preço do equipamento; não afeta a experiência", "A amplitude da área visível pelo usuário no ambiente virtual; um FOV maior aumenta a sensação de imersão", "O tempo de bateria do dispositivo", "A resolução do microfone"], correct: 1, explain: "Um campo de visão mais estreito reduz a sensação de estar realmente \"dentro\" do ambiente virtual." },
      { q: "O que causa a \"cinetose\" (enjoo) em algumas experiências de RV?", options: ["O uso de óculos de sol", "O conflito entre o movimento visual percebido e a ausência de movimento real sentido pelo corpo", "O volume alto do áudio", "A cor da interface"], correct: 1, explain: "O cérebro recebe sinais contraditórios entre o que os olhos veem e o que o corpo sente, causando desconforto." },
      { q: "O que é \"rastreamento posicional\" (positional tracking) em RV?", options: ["Um tipo de vírus", "A tecnologia que detecta a posição e o movimento do usuário no espaço físico para refletir isso no ambiente virtual", "Um recurso de economia de bateria", "Um tipo de conexão Wi-Fi"], correct: 1, explain: "É o que permite que, ao se abaixar ou andar na vida real, o movimento seja refletido no ambiente virtual." },
      { q: "Como a Realidade Aumentada é aplicada na manutenção industrial guiada?", options: ["Não tem aplicação nesse setor", "Sobrepondo instruções visuais digitais sobre o equipamento real, guiando o técnico durante o reparo", "Substituindo totalmente os técnicos humanos", "Apenas para fins decorativos"], correct: 1, explain: "Isso reduz erros e o tempo de treinamento necessário para reparos complexos." },
      { q: "O que diferencia dispositivos de RV \"standalone\" dos que dependem de um computador externo?", options: ["Não existe essa diferença", "Standalone processa tudo no próprio headset, sem precisar de um PC ou console conectado", "Standalone não usa nenhum tipo de tela", "Standalone é exclusivo para uso industrial"], correct: 1, explain: "Isso torna o equipamento mais portátil e acessível, sem exigir um computador potente à parte." },
    ],
  },
};

/* Metadados usados para montar a tela de seleção do quiz — nomes de exibição de cada área. */
const QUIZ_AREAS = [
  { id: "programacao", label: "Programação", code: "Setor 01" },
  { id: "ia", label: "Inteligência Artificial", code: "Setor 02" },
  { id: "ciberseguranca", label: "Cibersegurança", code: "Setor 03" },
  { id: "nuvem", label: "Cloud Computing", code: "Setor 04" },
  { id: "dados", label: "Ciência de Dados", code: "Setor 05" },
  { id: "redes", label: "Redes e Conectividade", code: "Setor 06" },
  { id: "iot", label: "Internet das Coisas", code: "Setor 07" },
  { id: "imersivas", label: "Realidade Virtual e Aumentada", code: "Setor 08" },
];

const QUIZ_DIFFICULTIES = [
  { id: "iniciante", label: "Iniciante", desc: "Conceitos do zero, sem pré-requisitos." },
  { id: "intermediario", label: "Intermediário", desc: "Para quem já reconhece os termos básicos." },
  { id: "avancado", label: "Avançado", desc: "Detalhes técnicos e termos mais específicos." },
];
